colorscheme gruvbox
set global tabstop     2
set global indentwidth 2

add-highlighter global/ number-lines -relative
hook global NormalKey <c-space> w
hook global NormalKey <c-q> q
map global normal '#' :comment-line<ret>
set global makecmd './build.sh'

def ide %{
	rename-client main
	set global jumpclient main

	new rename-client tools
	set global toolsclient tools
	set global docsclient tools

	hook global WinSetOption filetype=(c|cpp|h) %{
		set global formatcmd 'clang-format'
	  hook global BufWritePre .* %{format}
	  hook global BufWritePost .* %{
  	  make
	  }
	}
}

def test %{
  set buffer makecmd './test.sh'
}

def run %{
	tmux-terminal-window './run.sh'
}

hook global NormalKey <c-r> run
hook global BufCreate (.*/)?(\.kakrc\.local) %{
      set-option buffer filetype kak
}
try %{ source .kakrc.local }
source ~/.config/kak/find.kak
